### ISSUE TITLE
coverage report assistance/documentation please

### ISSUE THREAD

**Issue by neiljaywarner** [passsy/docker-flutterw#1]
i switched from   image: "cirrusci/flutter:2.10.3"
 to this container and it broke some things including code coverage.

This seems like it should be easy to fix but might be worth documetation/update?

it migth be breaking with
`    - ./flutterw test --machine --coverage | tojunit -o ut-report.xml
`

**Comment by neiljaywarner** [comment]
I think this poitns at the fact that soem flutter stuff uses "flutter" and some uses "dart" , and this has caused issues before with flutterw...

**Comment by passsy** [comment]
Still unsure what exactly broke for you. Any error message?

**Comment by neiljaywarner** [comment]
@passsy  
`$ ./flutterw test --machine --coverage | tojunit -o ut-report.xml
/home/dash/.pub-cache/bin/tojunit: 8: dart: not found
Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: Broken pipe, errno = 32)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:873:7)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:286:15)
#2      _rootRunUnary (dart:async/zone.dart:1434:47)`

**Comment by passsy** [comment]
I see. Nothing this docker container can fix though. You have to link the binary yourself.

Either add it to `PATH` or create an alias.

```bash
alias dart=/path/to/dart/binary/in/.flutter/bin/dart
```
```bash
export PATH="$PATH:/path/to/dart/binary/in/.flutter/bin/dart"
```

**Comment by neiljaywarner** [comment]
How could the doctor container change have broken it then

....sent from my phone

**Comment by passsy** [comment]
the `flutterw` container doesn't have flutter or dart installed. It has everything installed to run dart/flutter but not the actual SDK. Because I don't know where in the file system the `.flutter` directory will be located, I can't link the `dart` and `flutter` executable.
